# Use Node image
FROM node:current-alpine

# Set working dir
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy project files
COPY . .

# Expose port for dev server
EXPOSE 5173

# Run Vite dev server
CMD ["npm", "run", "dev"]
